services:
  - type: web
    name: blueprint api
    runtime: node
    repo: https://github.com/jabibamman/esgi.4a.render.blueprint.nodejs
    region: frankfurt # optional (defaults to oregon)
    buildCommand: npm install
    startCommand: npm start
    plan: free # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    rootDir: webdis
    healthCheckPath: /
    envVars:
      - key: DB_URL
        fromDatabase:
          name: elephant
          property: connectionString

databases:
  - name: elephant
    databaseName: jameslecoat # optional (Render may add a suffix)
    plan: free
